// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web; // Retorna opções configuradas para Web.
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android; // Retorna opções configuradas para Android.
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsqtbe4ZxXEfnnORFJc3bNpueOSNv5yPw',
    appId: '1:94868796553:web:263cb9fc9e7f22f4a88258',
    messagingSenderId: '94868796553',
    projectId: 'gasstation-andre',
    authDomain: 'gasstation-andre.firebaseapp.com',
    storageBucket: 'gasstation-andre.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARnHUudfubPNgAOwCTYXJkTfkD8_lBRW8',
    appId: '1:94868796553:android:e00245836bde1486a88258',
    messagingSenderId: '94868796553',
    projectId: 'gasstation-andre',
    storageBucket: 'gasstation-andre.appspot.com',
  );
}
